name: Latest activity

on:
  schedule:
    - cron: "0 */3 * * *"
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jamesgeorge007/github-activity-readme@master
        with:
          MAX_LINES: 8
          COMMIT_MSG: "chore: update recent activity"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
